### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by GouravSardana** [sugarlabs/SugarLabs_Social#2]
Any changes required for this project?

**Comment by quozl** [comment]
@avinashbharti97, will you be answering this question?

**Comment by avinashbharti97** [comment]
There are different ways in which you can make the contributions, some of which are:-
* Finding Bugs and Opening Issues for the same.
    * Frontend have many small bugs that can be easily regenerated.
    * Reply feature of comments is not working.
    * In Backend, Routing have some bugs.
* Some Features which can be implemented:-
    * Adding a Search bar and implement backend for the same in Feed app.
    * Adding User Profile Pic everywhere adjacent to User name.
    * Ajax Loading of feed [issue](https://github.com/sugarlabs/social/issues/4).
    * Adding Like, Bookmark Feature to posts and Blogs.
    * Implementing User Following Feature.

* Creating Issues explaining above points.

Hope this helps :)

**Comment by GouravSardana** [comment]
@ avinashbharti97 I have a query regarding search bar i.e search using  username or title name?

**Comment by avinashbharti97** [comment]
From my point of view having a search option which could perform a search of post title/ blog title/ tags/ username/ activity name/ project name/ softwares name etc. present in Feed view will serve well.
Also there is no hard and fast rule for any feature. If you want to add one, please propose it with the needed explanation, what you are going to do and why?

**Please don't start coding for features without getting a green signal to your proposed feature by mentor of this project.

Mentors are: Samson Goddy, Hrishi Patel, Jaskirat Singh, Pericherla Seetaramaraju.

Thanks
