### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by GouravSardana** [sugarlabs/SugarLabs_Social#3]
I installed all the requirements but there is an issue on postgres. So, i setup sqlite3 in my local and there is another issue regarding socialauth i.e site is on localhost and i can't signup.
so, i just created a user from admin and i can login through it.
Whats the changes and update for the projects @avinashbharti97 ?

**Comment by avinashbharti97** [comment]
can you please elaborate the problem coming with postgres?

**Comment by GouravSardana** [comment]
Here is the issue
22:55:44: Error: Error connecting to the server: fe_sendauth: no password supplied

**Comment by avinashbharti97** [comment]
Did you follow this? [settting up database](https://github.com/sugarlabs/SugarLabs_Social#setting-up-postgresql-database)

on running which command you are getting this error? 
or on which step this error is coming , if possible please share the screenshot.

**Comment by GouravSardana** [comment]
![image](https://user-images.githubusercontent.com/31731827/47039019-8455fb00-d1a0-11e8-830d-2d09fe366183.png)
Here is the error on pgadmin

**Comment by GouravSardana** [comment]
I tried all the steps as given by you in readme but database is not connected yet.
It shows django.db.utils.OperationalError: FATAL:  password authentication failed for user "root"

**Comment by avinashbharti97** [comment]
A new postgreSQL user should be created with the name 'username' and password 'password' .

Project settings variable depends on these names.

> here is the screenshot of settings variable

![setting variables](https://user-images.githubusercontent.com/22724583/47039873-80c37380-d1a2-11e8-9cc2-bb7dff5eb559.png)


* Use these commands to generate the user 
```
CREATE USER username WITH PASSWORD 'password';

GRANT ALL PRIVILEGES ON DATABASE database TO username;
```

**Comment by GouravSardana** [comment]
Done!! bro!
So, should we start ?

**Comment by avinashbharti97** [comment]
@GouravSardana  sure, I will update the issues with the features to be added and work to be done.

you can get an idea about the features to be implemented here [future development](https://medium.com/@avinashbharti97/summer-internship-with-sugar-labs-2018-d3046ebad6bd#7ac1) 
 you can also test the application and open the issues for the same :D
