### ISSUE TITLE
Ajax or lazy loading for feeds

### ISSUE THREAD

**Issue by avinashbharti97** [sugarlabs/SugarLabs_Social#4]
Currently, all the data is fetched at once in feed and that will take a lot of loading time.

*This problem can be solved by adding ajax loading of feeds on scrolling*

Best way to implement is to use Django pagination, something like this
![pagination](https://user-images.githubusercontent.com/22724583/47270217-1d608980-d586-11e8-9a94-6acc23937bd1.png)

**Comment by GouravSardana** [comment]
@avinashbharti97 you are facing an issue for that?

**Comment by rhl-bthr** [comment]
Fixed in 9156484
